package com.xworkz.app.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;



public class AlcoholRunner {
	public static void main(String[] args) {
		System.out.println("Invoking main in AlcoholRunner");
		Collection<AlcoholDTO> alcohols=new ArrayList<>();
		 AlcoholDTO vodka = new AlcoholDTO("Vodka", (byte) 40, (short) 750, 1, 1, 19.99f, 4.5, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO rum = new AlcoholDTO("Rum", (byte) 35, (short) 750, 1, 2, 15.99f, 4.2, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO whiskey = new AlcoholDTO("Whiskey", (byte) 45, (short) 750, 1, 3, 29.99f, 4.7, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO tequila = new AlcoholDTO("Tequila", (byte) 40, (short) 750, 1, 4, 24.99f, 4.3, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO gin = new AlcoholDTO("Gin", (byte) 40, (short) 750, 1, 5, 22.99f, 4.4, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO brandy = new AlcoholDTO("Brandy", (byte) 35, (short) 750, 1, 6, 19.99f, 4.1, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO champagne = new AlcoholDTO("Champagne", (byte) 12, (short) 750, 1, 7, 39.99f, 4.8, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO beer = new AlcoholDTO("Beer", (byte) 5, (short) 355, 1, 8, 5.99f, 4.0, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO wine = new AlcoholDTO("Wine", (byte) 14, (short) 750, 1, 9, 14.99f, 3.9, 'W', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO scotch = new AlcoholDTO("Scotch", (byte) 40, (short) 750, 1, 10, 34.99f, 4.6, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO bourbon = new AlcoholDTO("Bourbon", (byte) 45, (short) 750, 1, 11, 29.99f, 4.7, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO cognac = new AlcoholDTO("Cognac", (byte) 40, (short) 750, 1, 12, 39.99f, 4.8, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO sake = new AlcoholDTO("Sake", (byte) 15, (short) 750, 1, 13, 19.99f, 4.1, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO absinthe = new AlcoholDTO("Absinthe", (byte) 70, (short) 750, 1, 14, 44.99f, 4.9, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO cider = new AlcoholDTO("Cider", (byte) 5, (short) 355, 1, 15, 6.99f, 3.5, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO mead = new AlcoholDTO("Mead", (byte) 12, (short) 750, 1, 16, 12.99f, 3.7, 'M', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO port = new AlcoholDTO("Port", (byte) 20, (short) 750, 1, 17, 29.99f, 4.0, 'P', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO sherry = new AlcoholDTO("Sherry", (byte) 18, (short) 750, 1, 18, 25.99f, 4.2, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO prosecco = new AlcoholDTO("Prosecco", (byte) 11, (short) 750, 1, 19, 19.99f, 4.5, 'P', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO sambuca = new AlcoholDTO("Sambuca", (byte) 42, (short) 750, 10, 1, 25.99f, 4.5, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO amaretto = new AlcoholDTO("Amaretto", (byte) 28, (short) 500, 15, 2, 19.99f, 4.2, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO baijiu = new AlcoholDTO("Baijiu", (byte) 55, (short) 500, 5, 3, 39.99f, 3.8, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO pisco = new AlcoholDTO("Pisco", (byte) 40, (short) 750, 8, 4, 29.99f, 4.0, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO grappa = new AlcoholDTO("Grappa", (byte) 45, (short) 700, 7, 5, 34.99f, 4.1, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO aquavit = new AlcoholDTO("Aquavit", (byte) 40, (short) 750, 12, 6, 27.99f, 4.4, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO calvados = new AlcoholDTO("Calvados", (byte) 40, (short) 750, 6, 7, 31.99f, 4.3, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO armagnac = new AlcoholDTO("Armagnac", (byte) 40, (short) 750, 10, 8, 36.99f, 4.5, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO jenever = new AlcoholDTO("Jenever", (byte) 40, (short) 500, 9, 9, 23.99f, 4.0, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO kirsch = new AlcoholDTO("Kirsch", (byte) 40, (short) 750, 5, 10, 25.99f, 3.7, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO cachaca = new AlcoholDTO("Cachaça", (byte) 40, (short) 700, 12, 11, 21.99f, 3.9, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO ouzo = new AlcoholDTO("Ouzo", (byte) 40, (short) 750, 8, 12, 19.99f, 4.1, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO pastis = new AlcoholDTO("Pastis", (byte) 45, (short) 750, 10, 13, 24.99f, 4.3, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO soju = new AlcoholDTO("Soju", (byte) 25, (short) 360, 20, 14, 15.99f, 3.6, 'S', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO akvavit = new AlcoholDTO("Akvavit", (byte) 40, (short) 750, 8, 15, 27.99f, 4.2, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO irishWhiskey = new AlcoholDTO("Irish Whiskey", (byte) 40, (short) 750, 10, 16, 30.99f, 4.4, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO ryeWhiskey = new AlcoholDTO("Rye Whiskey", (byte) 45, (short) 750, 10, 17, 29.99f, 4.2, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO tennesseeWhiskey = new AlcoholDTO("Tennessee Whiskey", (byte) 40, (short) 750, 12, 18, 32.99f, 4.6, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO canadianWhiskey = new AlcoholDTO("Canadian Whiskey", (byte) 40, (short) 750, 12, 19, 28.99f, 4.3, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO blendedScotch = new AlcoholDTO("Blended Scotch", (byte) 40, (short) 750, 15, 20, 33.99f, 4.5, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO singleMaltScotch = new AlcoholDTO("Single Malt Scotch", (byte) 40, (short) 750, 1, 1, 50.0f, 4.5, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO aperol = new AlcoholDTO("Aperol", (byte) 11, (short) 750, 2, 2, 25.0f, 4.0, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO campari = new AlcoholDTO("Campari", (byte) 24, (short) 750, 3, 3, 30.0f, 4.2, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO limoncello = new AlcoholDTO("Limoncello", (byte) 30, (short) 500, 4, 4, 20.0f, 4.3, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO tripleSec = new AlcoholDTO("Triple Sec", (byte) 38, (short) 750, 5, 5, 35.0f, 4.4, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO cointreau = new AlcoholDTO("Cointreau", (byte) 40, (short) 750, 6, 6, 40.0f, 4.1, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO grandMarnier = new AlcoholDTO("Grand Marnier", (byte) 40, (short) 750, 7, 7, 45.0f, 4.6, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO vermouth = new AlcoholDTO("Vermouth", (byte) 15, (short) 750, 8, 8, 15.0f, 4.0, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO drambuie = new AlcoholDTO("Drambuie", (byte) 40, (short) 750, 9, 9, 50.0f, 4.5, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO galliano = new AlcoholDTO("Galliano", (byte) 42, (short) 750, 10, 10, 40.0f, 4.0, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO chambord = new AlcoholDTO("Chambord", (byte) 16, (short) 375, 11, 11, 25.0f, 4.2, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO baileys = new AlcoholDTO("Baileys", (byte) 17, (short) 750, 12, 12, 30.0f, 4.4, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO kahlua = new AlcoholDTO("Kahlúa", (byte) 20, (short) 750, 13, 13, 35.0f, 4.1, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO chartreuse = new AlcoholDTO("Chartreuse", (byte) 55, (short) 750, 14, 14, 60.0f, 4.6, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO frangelico = new AlcoholDTO("Frangelico", (byte) 20, (short) 750, 15, 15, 35.0f, 4.2, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO cremeDeMenthe = new AlcoholDTO("Crème de Menthe", (byte) 24, (short) 750, 16, 16, 40.0f, 4.4, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO curacao = new AlcoholDTO("Curaçao", (byte) 20, (short) 750, 17, 17, 35.0f, 4.0, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO midori = new AlcoholDTO("Midori", (byte) 20, (short) 750, 18, 18, 30.0f, 4.3, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO sloeGin = new AlcoholDTO("Sloe Gin", (byte) 25, (short) 750, 19, 19, 25.0f, 4.1, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO tripleSec1 = new AlcoholDTO("Triple Sec", (byte) 40, (short) 750, 5, 1L, 15.99f, 4.5, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO amaro = new AlcoholDTO("Amaro", (byte) 30, (short) 500, 3, 2L, 20.49f, 4.0, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO benedictine = new AlcoholDTO("Bénédictine", (byte) 40, (short) 750, 7, 3L, 25.99f, 4.8, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO goldschlager = new AlcoholDTO("Goldschläger", (byte) 43, (short) 750, 6, 4L, 30.99f, 4.7, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO jagermeister = new AlcoholDTO("Jägermeister", (byte) 35, (short) 750, 8, 5L, 22.99f, 4.2, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO salmiakkiKoskenkorva = new AlcoholDTO("Salmiakki Koskenkorva", (byte) 38, (short) 500, 2, 6L, 18.99f, 4.1, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO ouzo1 = new AlcoholDTO("Ouzo", (byte) 40, (short) 750, 4, 7L, 23.99f, 4.4, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO sambuca1 = new AlcoholDTO("Sambuca", (byte) 38, (short) 750, 5, 8L, 21.99f, 4.3, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO tiaMaria = new AlcoholDTO("Tia Maria", (byte) 20, (short) 750, 6, 9L, 28.99f, 4.6, 'L', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO pimms = new AlcoholDTO("Pimm's", (byte) 25, (short) 750, 10, 1, 15.99f, 4.5, 'L', true, LocalDate.of(2022, 10, 1), LocalDateTime.now());
	        AlcoholDTO pernod = new AlcoholDTO("Pernod", (byte) 40, (short) 700, 12, 2, 19.99f, 4.2, 'L', true, LocalDate.of(2022, 9, 15), LocalDateTime.now());
	        AlcoholDTO ricard = new AlcoholDTO("Ricard", (byte) 45, (short) 750, 8, 3, 17.99f, 4.0, 'L', true, LocalDate.of(2022, 8, 22), LocalDateTime.now());
	        AlcoholDTO poteen = new AlcoholDTO("Poteen", (byte) 90, (short) 500, 5, 4, 29.99f, 4.8, 'S', true, LocalDate.of(2022, 7, 10), LocalDateTime.now());
	        AlcoholDTO kahlua1 = new AlcoholDTO("Kahlúa", (byte) 20, (short) 750, 15, 5, 21.99f, 4.3, 'L', true, LocalDate.of(2022, 6, 5), LocalDateTime.now());
	        AlcoholDTO baileys1 = new AlcoholDTO("Bailey's Irish Cream", (byte) 17, (short) 750, 20, 6, 25.99f, 4.6, 'L', true, LocalDate.of(2022, 5, 14), LocalDateTime.now());
	        AlcoholDTO americanHoney = new AlcoholDTO("American Honey", (byte) 35, (short) 750, 18, 7, 27.99f, 4.4, 'W', true, LocalDate.of(2022, 4, 28), LocalDateTime.now());
	        AlcoholDTO southernComfort = new AlcoholDTO("Southern Comfort", (byte) 30, (short) 750, 22, 8, 24.99f, 4.1, 'W', true, LocalDate.of(2022, 3, 19), LocalDateTime.now());
	        AlcoholDTO fireball = new AlcoholDTO("Fireball", (byte) 33, (short) 750, 14, 9, 23.99f, 4.7, 'W', true, LocalDate.of(2022, 2, 11), LocalDateTime.now());
	        AlcoholDTO butterscotchSchnapps = new AlcoholDTO("Butterscotch Schnapps", (byte) 15, (short) 500, 9, 10, 18.99f, 3.9, 'S', true, LocalDate.of(2022, 1, 5), LocalDateTime.now());
	        AlcoholDTO peppermintSchnapps = new AlcoholDTO("Peppermint Schnapps", (byte) 15, (short) 500, 9, 11, 18.99f, 3.9, 'S', true, LocalDate.of(2021, 12, 10), LocalDateTime.now());
	        AlcoholDTO schnapps = new AlcoholDTO("Schnapps", (byte) 20, (short) 500, 12, 12, 21.99f, 4.0, 'S', true, LocalDate.of(2021, 11, 15), LocalDateTime.now());
	        AlcoholDTO chianti = new AlcoholDTO("Chianti", (byte) 14, (short) 750, 30, 13, 16.99f, 3.8, 'R', true, LocalDate.of(2021, 10, 25), LocalDateTime.now());
	        AlcoholDTO merlot = new AlcoholDTO("Merlot", (byte) 13, (short) 750, 28, 14, 15.99f, 3.7, 'R', true, LocalDate.of(2021, 9, 18), LocalDateTime.now());
	        AlcoholDTO pinotNoir = new AlcoholDTO("Pinot Noir", (byte) 12, (short) 750, 25, 15, 17.99f, 3.9, 'R', true, LocalDate.of(2021, 8, 22), LocalDateTime.now());
	        AlcoholDTO zinfandel = new AlcoholDTO("Zinfandel", (byte) 16, (short) 750, 22, 16, 19.99f, 4.1, 'R', true, LocalDate.of(2021, 7, 15), LocalDateTime.now());
	        AlcoholDTO malbec = new AlcoholDTO("Malbec", (byte) 15, (short) 750, 20, 17, 18.99f, 4.0, 'R', true, LocalDate.of(2021, 6, 30), LocalDateTime.now());
	        AlcoholDTO cabernetSauvignon = new AlcoholDTO("Cabernet Sauvignon", (byte) 14, (short) 750, 30, 18, 21.99f, 4.2, 'R', true, LocalDate.of(2021, 5, 11), LocalDateTime.now());
	        AlcoholDTO syrah = new AlcoholDTO("Syrah (Shiraz)", (byte) 15, (short) 750, 26, 19, 20.99f, 4.0, 'R', true, LocalDate.of(2021, 4, 19), LocalDateTime.now());
	        AlcoholDTO grenache = new AlcoholDTO("Grenache", (byte) 14, (short) 750, 25, 20, 19.99f, 4.1, 'R', true, LocalDate.of(2021, 3, 5), LocalDateTime.now());
	        AlcoholDTO sangiovese = new AlcoholDTO("Sangiovese", (byte) 12, (short) 750, 10, 1L, 29.99f, 4.5, 'R', true, LocalDate.of(2023, 10, 1), LocalDateTime.now());
	        AlcoholDTO tempranillo = new AlcoholDTO("Tempranillo", (byte) 13, (short) 750, 8, 2L, 25.99f, 4.2, 'R', true, LocalDate.of(2023, 9, 15), LocalDateTime.now());

	        AlcoholDTO riesling = new AlcoholDTO("Riesling", (byte) 11, (short) 750, 12, 3L, 21.99f, 4.7, 'W', true, LocalDate.of(2023, 8, 23), LocalDateTime.now());

	        AlcoholDTO sauvignonBlanc = new AlcoholDTO("Sauvignon Blanc", (byte) 12, (short) 750, 15, 4L, 19.99f, 4.6, 'W', true, LocalDate.of(2023, 7, 12), LocalDateTime.now());

	        AlcoholDTO chardonnay = new AlcoholDTO("Chardonnay", (byte) 13, (short) 750, 9, 5L, 23.99f, 4.3, 'W', true, LocalDate.of(2023, 6, 30), LocalDateTime.now());

	        AlcoholDTO pinotGrigio = new AlcoholDTO("Pinot Grigio", (byte) 11, (short) 750, 11, 6L, 20.99f, 4.4, 'W', true, LocalDate.of(2023, 5, 18), LocalDateTime.now());

	        AlcoholDTO cheninBlanc = new AlcoholDTO("Chenin Blanc", (byte) 12, (short) 750, 7, 7L, 18.99f, 4.8, 'W', true, LocalDate.of(2023, 4, 5), LocalDateTime.now());

	        AlcoholDTO gewurztraminer = new AlcoholDTO("Gewürztraminer", (byte) 13, (short) 750, 6, 8L, 22.99f, 4.9, 'W', true, LocalDate.of(2023, 3, 11), LocalDateTime.now());

	        AlcoholDTO viognier = new AlcoholDTO("Viognier", (byte) 12, (short) 750, 10, 9L, 24.99f, 4.7, 'W', true, LocalDate.of(2023, 2, 2), LocalDateTime.now());

	        AlcoholDTO moscato = new AlcoholDTO("Moscato", (byte) 11, (short) 750, 13, 10L, 17.99f, 4.6, 'W', true, LocalDate.of(2023, 1, 9), LocalDateTime.now());

	        AlcoholDTO prosecco1 = new AlcoholDTO("Prosecco", (byte) 11, (short) 750, 16, 11L, 27.99f, 4.5, 'S', true, LocalDate.of(2022, 12, 20), LocalDateTime.now());

	        AlcoholDTO cava = new AlcoholDTO("Cava", (byte) 12, (short) 750, 5, 12L, 21.99f, 4.4, 'S', true, LocalDate.of(2022, 11, 7), LocalDateTime.now());

			AlcoholDTO champagne1 = new AlcoholDTO("Champagne", (byte) 12, (short) 750, 8, 13L, 29.99f, 4.3, 'S', true, LocalDate.of(2022, 10, 1), LocalDateTime.now());

	        AlcoholDTO brut = new AlcoholDTO("Brut", (byte) 12, (short) 750, 4, 14L, 28.99f, 4.2, 'S', true, LocalDate.of(2022, 9, 15), LocalDateTime.now());

	        AlcoholDTO blancDeBlancs = new AlcoholDTO("Blanc de Blancs", (byte) 12, (short) 750, 3, 15L, 30.99f, 4.1, 'S', true, LocalDate.of(2022, 8, 23), LocalDateTime.now());

	        AlcoholDTO rose = new AlcoholDTO("Rosé", (byte) 11, (short) 750, 7, 16L, 22.99f, 4.0, 'R', true, LocalDate.of(2022, 7, 12), LocalDateTime.now());

	        AlcoholDTO sparklingWine = new AlcoholDTO("Sparkling Wine", (byte) 11, (short) 750, 9, 17L, 21.99f, 4.0, 'S', true, LocalDate.of(2022, 6, 30), LocalDateTime.now());

	        AlcoholDTO iceWine = new AlcoholDTO("Ice Wine", (byte) 12, (short) 375, 5, 18L, 59.99f, 4.8, 'D', true, LocalDate.of(2022, 5, 18), LocalDateTime.now());

	        AlcoholDTO madeira = new AlcoholDTO("Madeira", (byte) 20, (short) 750, 2, 19L, 34.99f, 4.2, 'D', true, LocalDate.of(2022, 4, 5), LocalDateTime.now());

	        AlcoholDTO marsala = new AlcoholDTO("Marsala", (byte) 18, (short) 750, 3, 20L, 31.99f, 4.3, 'D', true, LocalDate.of(2022, 3, 11), LocalDateTime.now());

	        AlcoholDTO drySherry = new AlcoholDTO("Dry Sherry", (byte) 17, (short) 750, 4, 21L, 27.99f, 4.4, 'D', true, LocalDate.of(2022, 2, 2), LocalDateTime.now());

	        AlcoholDTO creamSherry = new AlcoholDTO("Cream Sherry", (byte) 18, (short) 750, 5, 22L, 26.99f, 4.5, 'D', true, LocalDate.of(2022, 1, 9), LocalDateTime.now());

	        AlcoholDTO paleAle = new AlcoholDTO("Pale Ale", (byte) 6, (short) 330, 20, 23L, 9.99f, 4.0, 'A', true, LocalDate.of(2021, 12, 20), LocalDateTime.now());

	        AlcoholDTO indiaPaleAle = new AlcoholDTO("India Pale Ale (IPA)", (byte) 7, (short) 330, 18, 24L, 10.99f, 4.2, 'A', true, LocalDate.of(2021, 11, 7), LocalDateTime.now());

	        AlcoholDTO stout = new AlcoholDTO("Stout", (byte) 8, (short) 330, 15, 25L, 11.99f, 4.3, 'A', true, LocalDate.of(2021, 10, 1), LocalDateTime.now());
	        AlcoholDTO pilsner = new AlcoholDTO("Pilsner", (byte) 5, (short) 12, 10, 1, 5.99f, 4.5, 'A', true, LocalDate.of(2023, 10, 1), LocalDateTime.now());
	        AlcoholDTO wheatBeer = new AlcoholDTO("Wheat Beer", (byte) 4, (short) 16, 15, 2, 6.49f, 4.2, 'B', true, LocalDate.of(2023, 9, 15), LocalDateTime.now());
	        AlcoholDTO bock = new AlcoholDTO("Bock", (byte) 6, (short) 14, 12, 3, 6.99f, 4.8, 'A', true, LocalDate.of(2023, 10, 5), LocalDateTime.now());
	        AlcoholDTO porter = new AlcoholDTO("Porter", (byte) 7, (short) 12, 10, 4, 7.99f, 4.6, 'B', true, LocalDate.of(2023, 9, 20), LocalDateTime.now());
	        AlcoholDTO lambic = new AlcoholDTO("Lambic", (byte) 5, (short) 10, 8, 5, 8.49f, 4.0, 'A', true, LocalDate.of(2023, 8, 30), LocalDateTime.now());
	        AlcoholDTO kölsch = new AlcoholDTO("Kölsch", (byte) 4, (short) 11, 10, 6, 5.79f, 4.3, 'A', true, LocalDate.of(2023, 10, 10), LocalDateTime.now());
	        AlcoholDTO saison = new AlcoholDTO("Saison", (byte) 6, (short) 13, 9, 7, 7.29f, 4.7, 'B', true, LocalDate.of(2023, 10, 12), LocalDateTime.now());
	        AlcoholDTO radler = new AlcoholDTO("Radler", (byte) 3, (short) 12, 20, 8, 4.99f, 4.0, 'A', true, LocalDate.of(2023, 9, 25), LocalDateTime.now());
	        AlcoholDTO sake1 = new AlcoholDTO("Sake", (byte) 16, (short) 8, 5, 9, 14.99f, 15.0, 'C', true, LocalDate.of(2023, 7, 2), LocalDateTime.now());
	        AlcoholDTO plumWine = new AlcoholDTO("Plum Wine (Umeshu)", (byte) 12, (short) 8, 6, 10, 12.99f, 4.2, 'B', true, LocalDate.of(2023, 6, 15), LocalDateTime.now());
	        AlcoholDTO koreanSoju = new AlcoholDTO("Korean Soju", (byte) 20, (short) 9, 10, 11, 9.99f, 20.0, 'C', true, LocalDate.of(2023, 7, 5), LocalDateTime.now());
	        AlcoholDTO chineseBaijiu = new AlcoholDTO("Chinese Baijiu", (byte) 50, (short) 8, 8, 12, 19.99f, 45.0, 'C', true, LocalDate.of(2023, 8, 10), LocalDateTime.now());
	        AlcoholDTO sotol = new AlcoholDTO("Sotol", (byte) 45, (short) 6, 7, 13, 16.99f, 4.9, 'B', true, LocalDate.of(2023, 9, 28), LocalDateTime.now());
	        AlcoholDTO rakia = new AlcoholDTO("Rakia", (byte) 40, (short) 7, 8, 14, 13.99f, 4.5, 'B', true, LocalDate.of(2023, 10, 15), LocalDateTime.now());
	        AlcoholDTO aguardiente = new AlcoholDTO("Aguardiente", (byte) 30, (short) 6, 6, 15, 11.99f, 4.3, 'B', true, LocalDate.of(2023, 10, 22), LocalDateTime.now());
	        AlcoholDTO horchata = new AlcoholDTO("Horchata", (byte) 0, (short) 16, 10, 16, 6.99f, 0.0, 'A', true, LocalDate.of(2023, 9, 10), LocalDateTime.now());
	        AlcoholDTO eggnog = new AlcoholDTO("Eggnog", (byte) 10, (short) 8, 20, 17, 5.49f, 4.0, 'A', true, LocalDate.of(2023, 11, 1), LocalDateTime.now());
	        AlcoholDTO kombucha = new AlcoholDTO("Kombucha", (byte) 0, (short) 16, 15, 18, 4.99f, 0.0, 'A', true, LocalDate.of(2023, 8, 5), LocalDateTime.now());
	        AlcoholDTO mead1 = new AlcoholDTO("Mead", (byte) 12, (short) 12, 12, 19, 10.99f, 3.9, 'A', true, LocalDate.of(2023, 10, 18), LocalDateTime.now());
	        AlcoholDTO moonshine = new AlcoholDTO("Moonshine", (byte) 50, (short) 10, 5, 20, 8.99f, 4.8, 'B', true, LocalDate.of(2023, 9, 8), LocalDateTime.now());
	        AlcoholDTO glogg = new AlcoholDTO("Glogg", (byte) 15, (short) 8, 7, 21, 9.49f, 4.6, 'B', true, LocalDate.of(2023, 11, 10), LocalDateTime.now());
	        AlcoholDTO tiswin = new AlcoholDTO("Tiswin", (byte) 3, (short) 14, 8, 22, 6.29f, 3.5, 'A', true, LocalDate.of(2023, 10, 9), LocalDateTime.now());
	        AlcoholDTO chicha = new AlcoholDTO("Chicha", (byte) 5, (short) 16, 9, 23, 7.99f, 4.0, 'A', true, LocalDate.of(2023, 9, 12), LocalDateTime.now());
	        AlcoholDTO pulque = new AlcoholDTO("Pulque", (byte) 5, (short) 14, 10, 24, 8.99f, 4.2, 'A', true, LocalDate.of(2023, 10, 7), LocalDateTime.now());
	        AlcoholDTO malort = new AlcoholDTO("Malört", (byte) 35, (short) 8, 6, 25, 12.99f, 2.0, 'C', true, LocalDate.of(2023, 8, 15), LocalDateTime.now());
	        AlcoholDTO akvavit1 = new AlcoholDTO("Akvavit", (byte) 40, (short) 750, 10, 1, 29.99f, 4.5, 'A', true, LocalDate.of(2022, 10, 15), LocalDateTime.now());
	        AlcoholDTO gammelDansk = new AlcoholDTO("Gammel Dansk", (byte) 38, (short) 700, 8, 2, 27.99f, 4.2, 'A', true, LocalDate.of(2022, 9, 20), LocalDateTime.now());
	        AlcoholDTO palinka = new AlcoholDTO("Pálinka", (byte) 48, (short) 500, 5, 3, 35.99f, 4.8, 'P', true, LocalDate.of(2022, 8, 5), LocalDateTime.now());
	        AlcoholDTO rakija = new AlcoholDTO("Rakija", (byte) 40, (short) 750, 7, 4, 32.99f, 4.4, 'R', true, LocalDate.of(2022, 7, 10), LocalDateTime.now());
	        AlcoholDTO pimmsCup = new AlcoholDTO("Pimm's Cup", (byte) 25, (short) 750, 12, 5, 21.99f, 4.0, 'P', true, LocalDate.of(2022, 6, 25), LocalDateTime.now());
	        AlcoholDTO whiskeySour = new AlcoholDTO("Whiskey Sour", (byte) 30, (short) 700, 9, 6, 24.99f, 4.1, 'W', true, LocalDate.of(2022, 5, 30), LocalDateTime.now());
	        AlcoholDTO martini = new AlcoholDTO("Martini", (byte) 40, (short) 750, 11, 7, 28.99f, 4.3, 'M', true, LocalDate.of(2022, 4, 15), LocalDateTime.now());
	        AlcoholDTO margarita = new AlcoholDTO("Margarita", (byte) 20, (short) 700, 6, 8, 22.99f, 3.8, 'M', true, LocalDate.of(2022, 3, 8), LocalDateTime.now());
	        AlcoholDTO daiquiri = new AlcoholDTO("Daiquiri", (byte) 25, (short) 750, 8, 9, 25.99f, 4.0, 'D', true, LocalDate.of(2022, 2, 20), LocalDateTime.now());
	        AlcoholDTO mojito = new AlcoholDTO("Mojito", (byte) 30, (short) 700, 10, 10, 27.99f, 4.2, 'M', true, LocalDate.of(2022, 1, 5), LocalDateTime.now());
	        AlcoholDTO pinaColada = new AlcoholDTO("Piña Colada", (byte) 20, (short) 750, 7, 11, 23.99f, 3.9, 'P', true, LocalDate.of(2021, 12, 10), LocalDateTime.now());
	        AlcoholDTO maiTai = new AlcoholDTO("Mai Tai", (byte) 25, (short) 700, 9, 12, 26.99f, 4.1, 'M', true, LocalDate.of(2021, 11, 15), LocalDateTime.now());
	        AlcoholDTO longIslandIcedTea = new AlcoholDTO("Long Island Iced Tea", (byte) 30, (short) 750, 12, 13, 30.99f, 4.4, 'L', true, LocalDate.of(2021, 10, 20), LocalDateTime.now());
	        AlcoholDTO moscowMule = new AlcoholDTO("Moscow Mule", (byte) 25, (short) 700, 8, 14, 25.99f, 4.0, 'M', true, LocalDate.of(2021, 9, 25), LocalDateTime.now());
	        AlcoholDTO sidecar = new AlcoholDTO("Sidecar", (byte) 35, (short) 750, 10, 15, 29.99f, 4.3, 'S', true, LocalDate.of(2021, 8, 30), LocalDateTime.now());
	        AlcoholDTO caipirinha = new AlcoholDTO("Caipirinha", (byte) 40, (short) 200, 10, 1, 10.99f, 4.5, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO cosmopolitan = new AlcoholDTO("Cosmopolitan", (byte) 25, (short) 150, 8, 2, 8.99f, 4.2, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO oldFashioned = new AlcoholDTO("Old Fashioned", (byte) 35, (short) 180, 12, 3, 12.49f, 4.8, 'O', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO negroni = new AlcoholDTO("Negroni", (byte) 30, (short) 160, 9, 4, 9.75f, 4.3, 'N', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO whiteRussian = new AlcoholDTO("White Russian", (byte) 20, (short) 140, 7, 5, 7.25f, 4.0, 'W', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO bloodyMary = new AlcoholDTO("Bloody Mary", (byte) 25, (short) 150, 8, 6, 8.50f, 4.1, 'B', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO blueLagoon = new AlcoholDTO("Blue Lagoon", (byte) 20, (short) 160, 10, 7, 10.99f, 4.4, 'B', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO blackRussian = new AlcoholDTO("Black Russian", (byte) 30, (short) 180, 11, 8, 11.25f, 4.7, 'B', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO sexOnTheBeach = new AlcoholDTO("Sex on the Beach", (byte) 25, (short) 170, 9, 9, 9.75f, 4.2, 'S', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO zombie = new AlcoholDTO("Zombie", (byte) 45, (short) 220, 12, 10, 12.99f, 4.6, 'Z', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO hurricane = new AlcoholDTO("Hurricane", (byte) 40, (short) 210, 11, 11, 11.50f, 4.5, 'H', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO sazerac = new AlcoholDTO("Sazerac", (byte) 35, (short) 190, 10, 12, 10.75f, 4.3, 'S', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO corpseReviver = new AlcoholDTO("Corpse Reviver", (byte) 30, (short) 160, 9, 13, 9.99f, 4.4, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO grasshopper = new AlcoholDTO("Grasshopper", (byte) 20, (short) 150, 8, 14, 8.25f, 4.1, 'G', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO tomCollins = new AlcoholDTO("Tom Collins", (byte) 25, (short) 170, 9, 15, 9.75f, 4.2, 'T', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO mintJulep = new AlcoholDTO("Mint Julep", (byte) 5, (short) 150, 10, 1, 8.99f, 4.5, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO sling = new AlcoholDTO("Sling", (byte) 6, (short) 200, 8, 2, 9.99f, 4.2, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO paloma = new AlcoholDTO("Paloma", (byte) 7, (short) 250, 12, 3, 7.99f, 4.0, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO tequilaSunrise = new AlcoholDTO("Tequila Sunrise", (byte) 8, (short) 300, 15, 4, 6.99f, 3.8, 'D', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO alabamaSlammer = new AlcoholDTO("Alabama Slammer", (byte) 6, (short) 200, 10, 5, 8.49f, 4.4, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO b52 = new AlcoholDTO("B-52", (byte) 7, (short) 250, 8, 6, 9.49f, 4.6, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO kamikaze = new AlcoholDTO("Kamikaze", (byte) 5, (short) 150, 14, 7, 7.49f, 4.2, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO tequilaSlammer = new AlcoholDTO("Tequila Slammer", (byte) 8, (short) 300, 9, 8, 10.99f, 4.8, 'D', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO godfather = new AlcoholDTO("Godfather", (byte) 9, (short) 350, 7, 9, 11.99f, 4.9, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO rustyNail = new AlcoholDTO("Rusty Nail", (byte) 30, (short) 150, 1, 1, 10.99f, 4.5, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO robRoy = new AlcoholDTO("Rob Roy", (byte) 25, (short) 140, 1, 2, 9.99f, 4.2, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO manhattan = new AlcoholDTO("Manhattan", (byte) 20, (short) 120, 1, 3, 8.99f, 4.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO plantersPunch = new AlcoholDTO("Planter's Punch", (byte) 15, (short) 110, 1, 4, 7.99f, 3.8, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO singaporeSling = new AlcoholDTO("Singapore Sling", (byte) 18, (short) 130, 1, 5, 9.49f, 4.1, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO darkAndStormy = new AlcoholDTO("Dark and Stormy", (byte) 22, (short) 140, 1, 6, 9.99f, 4.3, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO whiteWineSpritzer = new AlcoholDTO("White Wine Spritzer", (byte) 12, (short) 100, 1, 7, 6.99f, 3.5, 'W', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO sangria = new AlcoholDTO("Sangria", (byte) 14, (short) 110, 1, 8, 7.49f, 3.7, 'W', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO blackVelvet = new AlcoholDTO("Black Velvet", (byte) 28, (short) 160, 1, 9, 11.99f, 4.6, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO snakebite = new AlcoholDTO("Snakebite", (byte) 15, (short) 120, 1, 10, 7.99f, 3.9, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO brassMonkey = new AlcoholDTO("Brass Monkey", (byte) 12, (short) 110, 1, 11, 6.99f, 3.6, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO arnoldPalmer = new AlcoholDTO("Arnold Palmer", (byte) 8, (short) 90, 1, 12, 5.99f, 3.0, 'W', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO boilermaker = new AlcoholDTO("Boilermaker", (byte) 25, (short) 140, 1, 13, 9.99f, 4.1, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO depthCharge = new AlcoholDTO("Depth Charge", (byte) 20, (short) 130, 1, 14, 8.99f, 3.9, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO whiskeySmash = new AlcoholDTO("Whiskey Smash", (byte) 18, (short) 120, 1, 15, 7.99f, 4.2, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO vesper = new AlcoholDTO("Vesper", (byte) 30, (short) 150, 1, 16, 10.99f, 4.4, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO tomAndJerry = new AlcoholDTO("Tom and Jerry", (byte) 12, (short) 100, 1, 17, 6.99f, 3.7, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO gibson = new AlcoholDTO("Gibson", (byte) 16, (short) 120, 1, 18, 8.49f, 3.9, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO blackAndTan = new AlcoholDTO("Black and Tan", (byte) 5, (short) 12, 1, 1, 7.99f, 4.5, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO greyhound = new AlcoholDTO("Greyhound", (byte) 8, (short) 10, 1, 2, 6.99f, 4.0, 'G', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO pinkGin = new AlcoholDTO("Pink Gin", (byte) 6, (short) 8, 1, 3, 8.99f, 4.2, 'P', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO bocceBall = new AlcoholDTO("Bocce Ball", (byte) 4, (short) 14, 1, 4, 5.99f, 3.8, 'B', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO redSnapper = new AlcoholDTO("Red Snapper", (byte) 7, (short) 10, 1, 5, 7.49f, 4.1, 'R', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO elDiablo = new AlcoholDTO("El Diablo", (byte) 6, (short) 9, 1, 6, 6.49f, 3.9, 'E', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO kirRoyale = new AlcoholDTO("Kir Royale", (byte) 5, (short) 7, 1, 7, 9.49f, 4.4, 'K', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO horsesNeck = new AlcoholDTO("Horse's Neck", (byte) 5, (short) 6, 1, 8, 7.99f, 4.3, 'H', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO caipiroska = new AlcoholDTO("Caipiroska", (byte) 7, (short) 8, 1, 9, 8.99f, 4.2, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO whiskeyCollins = new AlcoholDTO("Whiskey Collins", (byte) 8, (short) 10, 1, 10, 9.99f, 4.6, 'W', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO goldenCadillac = new AlcoholDTO("Golden Cadillac", (byte) 7, (short) 7, 1, 11, 9.49f, 4.1, 'G', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO zombie1 = new AlcoholDTO("Zombie", (byte) 9, (short) 12, 1, 12, 8.99f, 4.8, 'Z', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO chocolateMartini = new AlcoholDTO("Chocolate Martini", (byte) 6, (short) 6, 1, 13, 7.99f, 4.3, 'M', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO painkiller = new AlcoholDTO("Painkiller", (byte) 8, (short) 8, 1, 14, 8.49f, 4.5, 'P', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO aviation = new AlcoholDTO("Aviation", (byte) 7, (short) 6, 1, 15, 7.99f, 4.2, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO robRoy1 = new AlcoholDTO("Rob Roy", (byte) 40, (short) 250, 10, 1, 8.99f, 4.5, 'A', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO blackthorn = new AlcoholDTO("Blackthorn", (byte) 35, (short) 350, 15, 2, 9.99f, 4.0, 'B', true, LocalDate.of(2023, 10, 28), LocalDateTime.now());
	        AlcoholDTO julep = new AlcoholDTO("Julep", (byte) 30, (short) 300, 12, 3, 7.99f, 4.2, 'C', true, LocalDate.of(2023, 10, 27), LocalDateTime.now());
	        AlcoholDTO goldRush = new AlcoholDTO("Gold Rush", (byte) 45, (short) 200, 8, 4, 10.99f, 4.8, 'D', true, LocalDate.of(2023, 10, 26), LocalDateTime.now());
	        AlcoholDTO oaxacaOldFashioned = new AlcoholDTO("Oaxaca Old Fashioned", (byte) 50, (short) 280, 11, 5, 12.99f, 4.7, 'E', true, LocalDate.of(2023, 10, 25), LocalDateTime.now());
	        AlcoholDTO cloverClub = new AlcoholDTO("Clover Club", (byte) 35, (short) 220, 9, 6, 8.49f, 4.6, 'F', true, LocalDate.of(2023, 10, 24), LocalDateTime.now());
	        AlcoholDTO vieuxCarre = new AlcoholDTO("Vieux Carré", (byte) 40, (short) 330, 14, 7, 9.75f, 4.4, 'G', true, LocalDate.of(2023, 10, 23), LocalDateTime.now());
	        AlcoholDTO stinger = new AlcoholDTO("Stinger", (byte) 32, (short) 270, 13, 8, 7.95f, 4.3, 'H', true, LocalDate.of(2023, 10, 22), LocalDateTime.now());
	        AlcoholDTO rumSwizzle = new AlcoholDTO("Rum Swizzle", (byte) 38, (short) 310, 10, 9, 9.49f, 4.6, 'I', true, LocalDate.of(2023, 10, 21), LocalDateTime.now());
	        AlcoholDTO zombie11 = new AlcoholDTO("Zombie", (byte) 45, (short) 320, 12, 10, 11.25f, 4.9, 'J', true, LocalDate.of(2023, 10, 20), LocalDateTime.now());
	        AlcoholDTO rustyNail1 = new AlcoholDTO("Rusty Nail", (byte) 40, (short) 280, 10, 11, 8.99f, 4.7, 'K', true, LocalDate.of(2023, 10, 19), LocalDateTime.now());
	        AlcoholDTO maryPickford = new AlcoholDTO("Mary Pickford", (byte) 35, (short) 240, 11, 12, 7.99f, 4.8, 'L', true, LocalDate.of(2023, 10, 18), LocalDateTime.now());
	        AlcoholDTO hemingwayDaiquiri = new AlcoholDTO("Hemingway Daiquiri", (byte) 45, (short) 290, 13, 13, 9.49f, 4.6, 'M', true, LocalDate.of(2023, 10, 17), LocalDateTime.now());
	        AlcoholDTO moscowMule1 = new AlcoholDTO("Moscow Mule", (byte) 35, (short) 250, 9, 14, 7.75f, 4.4, 'N', true, LocalDate.of(2023, 10, 16), LocalDateTime.now());
	        AlcoholDTO maiTai1 = new AlcoholDTO("Mai Tai", (byte) 40, (short) 270, 12, 15, 8.95f, 4.5, 'O', true, LocalDate.of(2023, 10, 15), LocalDateTime.now());
	        AlcoholDTO mojito1 = new AlcoholDTO("Mojito", (byte) 35, (short) 290, 11, 16, 7.49f, 4.7, 'P', true, LocalDate.of(2023, 10, 14), LocalDateTime.now());
	        AlcoholDTO sidecar1 = new AlcoholDTO("Sidecar", (byte) 38, (short) 260, 10, 17, 8.75f, 4.3, 'Q', true, LocalDate.of(2023, 10, 13), LocalDateTime.now());
	        AlcoholDTO corpseReviver1 = new AlcoholDTO("Corpse Reviver", (byte) 42, (short) 280, 11, 18, 9.25f, 4.9, 'R', true, LocalDate.of(2023, 10, 12), LocalDateTime.now());
	        AlcoholDTO tomCollins1 = new AlcoholDTO("Tom Collins", (byte) 35, (short) 300, 13, 19, 7.95f, 4.8, 'S', true, LocalDate.of(2023, 10, 11), LocalDateTime.now());
	        AlcoholDTO sazerac1 = new AlcoholDTO("Sazerac", (byte) 45, (short) 250, 12, 20, 8.99f, 4.6, 'T', true, LocalDate.of(2023, 10, 10), LocalDateTime.now());
	        AlcoholDTO paloma1 = new AlcoholDTO("Paloma", (byte) 10, (short) 200, 1, 1L, 8.99f, 4.5, 'T', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO negroni1 = new AlcoholDTO("Negroni", (byte) 25, (short) 150, 2, 2L, 12.99f, 4.2, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO boulevardier = new AlcoholDTO("Boulevardier", (byte) 28, (short) 180, 3, 3L, 14.99f, 4.6, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO piscoSour = new AlcoholDTO("Pisco Sour", (byte) 15, (short) 250, 4, 4L, 10.99f, 4.3, 'T', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO piscoPunch = new AlcoholDTO("Pisco Punch", (byte) 20, (short) 280, 5, 5L, 11.99f, 4.4, 'T', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO newYorkSour = new AlcoholDTO("New York Sour", (byte) 22, (short) 220, 6, 6L, 12.49f, 4.7, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO vodkaCollins = new AlcoholDTO("Vodka Collins", (byte) 18, (short) 240, 7, 7L, 9.99f, 4.0, 'T', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO french75 = new AlcoholDTO("French 75", (byte) 15, (short) 190, 8, 8L, 13.49f, 4.6, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO bellini = new AlcoholDTO("Bellini", (byte) 12, (short) 170, 9, 9L, 8.49f, 4.2, 'T', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO darkNStormy = new AlcoholDTO("Dark 'n' Stormy", (byte) 20, (short) 250, 10, 10L, 11.99f, 4.4, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO cloverClub1 = new AlcoholDTO("Clover Club", (byte) 18, (short) 230, 11, 11L, 10.99f, 4.3, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO corpseReviver11 = new AlcoholDTO("Corpse Reviver", (byte) 23, (short) 200, 12, 12L, 13.99f, 4.5, 'T', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO goldRush1 = new AlcoholDTO("Gold Rush", (byte) 15, (short) 180, 13, 13L, 9.99f, 4.1, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO daiquiri1 = new AlcoholDTO("Daiquiri", (byte) 18, (short) 220, 14, 14L, 10.49f, 4.4, 'T', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO sazerac11 = new AlcoholDTO("Sazerac11", (byte) 28, (short) 250, 15, 15L, 15.99f, 4.8, 'C', true, LocalDate.of(2023, 10, 29), LocalDateTime.now());
	        AlcoholDTO zombie22 = new AlcoholDTO("Zombie22", (byte) 10, (short) 250, 10, 1, 12.99f, 4.5, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO mojito11 = new AlcoholDTO("Mojito", (byte) 5, (short) 200, 15, 2, 9.99f, 4.2, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO maiTai11 = new AlcoholDTO("Mai Tai", (byte) 15, (short) 300, 20, 3, 14.99f, 4.7, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO moscowMule11 = new AlcoholDTO("Moscow Mule", (byte) 8, (short) 275, 12, 4, 11.99f, 4.0, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO sidecar11 = new AlcoholDTO("Sidecar", (byte) 12, (short) 220, 18, 5, 13.99f, 4.4, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO whiteLady = new AlcoholDTO("White Lady", (byte) 12, (short) 240, 15, 6, 12.99f, 4.3, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO oldCuban = new AlcoholDTO("Old Cuban", (byte) 15, (short) 275, 10, 7, 14.99f, 4.6, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO frenchConnection = new AlcoholDTO("French Connection", (byte) 12, (short) 250, 10, 8, 12.99f, 4.3, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO wardEight = new AlcoholDTO("Ward Eight", (byte) 10, (short) 230, 15, 9, 11.99f, 4.1, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO plantersPunch1 = new AlcoholDTO("Planters Punch", (byte) 14, (short) 300, 8, 10, 13.99f, 4.5, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO kamikaze1 = new AlcoholDTO("Kamikaze", (byte) 10, (short) 180, 12, 11, 10.99f, 4.2, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO godfather1 = new AlcoholDTO("Godfather", (byte) 14, (short) 270, 10, 12, 12.99f, 4.4, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO tequilaSlammer1 = new AlcoholDTO("Tequila Slammer", (byte) 10, (short) 220, 14, 13, 11.99f, 4.3, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO alabamaSlammer1 = new AlcoholDTO("Alabama Slammer", (byte) 12, (short) 240, 12, 14, 12.99f, 4.4, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO seaBreeze = new AlcoholDTO("Sea Breeze", (byte) 8, (short) 190, 16, 15, 10.99f, 4.1, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO cubaLibre = new AlcoholDTO("Cuba Libre", (byte) 10, (short) 220, 18, 16, 11.99f, 4.2, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO blackRussian1 = new AlcoholDTO("Black Russian", (byte) 10, (short) 240, 15, 17, 11.99f, 4.3, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO caipirissima = new AlcoholDTO("Caipirissima", (byte) 14, (short) 260, 12, 18, 12.99f, 4.5, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO darkNStormy1 = new AlcoholDTO("Dark 'n' Stormy", (byte) 10, (short) 220, 20, 19, 11.99f, 4.2, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO kir = new AlcoholDTO("Kir", (byte) 6, (short) 180, 14, 20, 9.99f, 4.0, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO whiteRussian1 = new AlcoholDTO("White Russian", (byte) 10, (short) 250, 1, 1L, 9.99f, 4.5, 'V', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO chocolateMartini1 = new AlcoholDTO("Chocolate Martini", (byte) 12, (short) 200, 1, 2L, 10.99f, 4.7, 'C', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO aviation1 = new AlcoholDTO("Aviation", (byte) 15, (short) 300, 1, 3L, 12.99f, 4.2, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO whiskeySour1 = new AlcoholDTO("Whiskey Sour", (byte) 12, (short) 250, 1, 4L, 8.99f, 4.0, 'W', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO amarettoSour = new AlcoholDTO("Amaretto Sour", (byte) 10, (short) 220, 1, 5L, 9.49f, 4.2, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO mojito111 = new AlcoholDTO("Mojito", (byte) 8, (short) 300, 1, 6L, 7.99f, 4.6, 'M', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO daiquiri11 = new AlcoholDTO("Daiquiri", (byte) 10, (short) 220, 1, 7L, 8.99f, 4.4, 'D', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO pinaColada1 = new AlcoholDTO("Piña Colada", (byte) 9, (short) 280, 1, 8L, 9.99f, 4.3, 'P', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO margarita1 = new AlcoholDTO("Margarita", (byte) 11, (short) 240, 1, 9L, 10.49f, 4.5, 'M', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO martini1 = new AlcoholDTO("Martini", (byte) 14, (short) 210, 1, 10L, 11.99f, 4.7, 'M', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO negroni11 = new AlcoholDTO("Negroni", (byte) 18, (short) 180, 1, 11L, 12.99f, 4.1, 'N', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO sazerac111 = new AlcoholDTO("Sazerac", (byte) 16, (short) 190, 1, 12L, 12.49f, 4.0, 'S', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO manhattan1 = new AlcoholDTO("Manhattan", (byte) 15, (short) 210, 1, 13L, 11.99f, 4.4, 'M', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO oldFashioned1 = new AlcoholDTO("Old Fashioned", (byte) 14, (short) 240, 1, 14L, 10.99f, 4.3, 'O', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO whiskeySour2 = new AlcoholDTO("Whiskey Sour", (byte) 12, (short) 250, 1, 15L, 8.99f, 4.0, 'W', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO tomCollins2 = new AlcoholDTO("Tom Collins2", (byte) 2, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO caipirinha2 = new AlcoholDTO("Caipirinha2", (byte) 2, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO mojito3 = new AlcoholDTO("Mojito3", (byte) 3, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO piscoSour3 = new AlcoholDTO("Pisco Sour3", (byte) 3, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO daiquiri4 = new AlcoholDTO("Daiquiri4", (byte) 4, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO pinaColada4 = new AlcoholDTO("Piña Colada4", (byte) 4, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO margarita5 = new AlcoholDTO("Margarita5", (byte) 5, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO moscowMule6 = new AlcoholDTO("Moscow Mule6", (byte) 6, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO negroni7 = new AlcoholDTO("Negroni7", (byte) 7, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO sidecar8 = new AlcoholDTO("Sidecar8", (byte) 8, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO maiTai9 = new AlcoholDTO("Mai Tai9", (byte) 9, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO zombie7 = new AlcoholDTO("Zombie7", (byte) 7, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO sazerac6 = new AlcoholDTO("Sazerac6", (byte) 6, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO boulevardier5 = new AlcoholDTO("Boulevardier5", (byte) 5, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());
	        AlcoholDTO blackRussian44 = new AlcoholDTO("Black Russian44", (byte) 44, (short) 0, 0, 0, 0.0f, 0.0, 'A', true, LocalDate.now(), LocalDateTime.now());

	        
	        
	        alcohols.add(vodka);
	        alcohols.add(rum);
	        alcohols.add(whiskey);
	        alcohols.add(tequila);
	        alcohols.add(gin);
	        alcohols.add(brandy);
	        alcohols.add(champagne1);
	        alcohols.add(beer);
	        alcohols.add(wine);
	        alcohols.add(scotch);
	        alcohols.add(bourbon);
	        alcohols.add(cognac);
	        alcohols.add(sake1);
	        alcohols.add(absinthe);
	        alcohols.add(cider);
	        alcohols.add(mead1);
	        alcohols.add(port);
	        alcohols.add(sherry);
	        alcohols.add(prosecco1);
	        alcohols.add(sambuca1);
	        alcohols.add(amaretto);
	        alcohols.add(baijiu);
	        alcohols.add(pisco);
	        alcohols.add(grappa);
	        alcohols.add(aquavit);
	        alcohols.add(calvados);
	        alcohols.add(armagnac);
	        alcohols.add(jenever);
	        alcohols.add(kirsch);
	        alcohols.add(cachaca);
	        alcohols.add(ouzo1);
	        alcohols.add(pastis);
	        alcohols.add(soju);
	        alcohols.add(akvavit1);
	        alcohols.add(irishWhiskey);
	        alcohols.add(ryeWhiskey);
	        alcohols.add(tennesseeWhiskey);
	        alcohols.add(canadianWhiskey);
	        alcohols.add(blendedScotch);
	        alcohols.add(singleMaltScotch);
	        alcohols.add(aperol);
	        alcohols.add(campari);
	        alcohols.add(limoncello);
	        alcohols.add(tripleSec1);
	        alcohols.add(cointreau);
	        alcohols.add(grandMarnier);
	        alcohols.add(vermouth);
	        alcohols.add(drambuie);
	        alcohols.add(galliano);
	        alcohols.add(chambord);
	        alcohols.add(baileys1);
	        alcohols.add(kahlua1);
	        alcohols.add(chartreuse);
	        alcohols.add(frangelico);
	        alcohols.add(cremeDeMenthe);
	        alcohols.add(curacao);
	        alcohols.add(midori);
	        alcohols.add(sloeGin);
	        alcohols.add(tripleSec);
	        alcohols.add(amaro);
	        alcohols.add(benedictine);
	        alcohols.add(goldschlager);
	        alcohols.add(jagermeister);
	        alcohols.add(salmiakkiKoskenkorva);
	        alcohols.add(ouzo);
	        alcohols.add(sambuca);
	        alcohols.add(tiaMaria);
	        alcohols.add(pimms);
	        alcohols.add(pernod);
	        alcohols.add(ricard);
	        alcohols.add(poteen);
	        alcohols.add(kahlua);
	        alcohols.add(baileys);
	        alcohols.add(americanHoney);
	        alcohols.add(southernComfort);
	        alcohols.add(fireball);
	        alcohols.add(butterscotchSchnapps);
	        alcohols.add(peppermintSchnapps);
	        alcohols.add(schnapps);
	        alcohols.add(chianti);
	        alcohols.add(merlot);
	        alcohols.add(pinotNoir);
	        alcohols.add(zinfandel);
	        alcohols.add(malbec);
	        alcohols.add(cabernetSauvignon);
	        alcohols.add(syrah);
	        alcohols.add(grenache);
	        alcohols.add(sangiovese);
	        alcohols.add(tempranillo);
	        alcohols.add(riesling);
	        alcohols.add(sauvignonBlanc);
	        alcohols.add(chardonnay);
	        alcohols.add(pinotGrigio);
	        alcohols.add(cheninBlanc);
	        alcohols.add(gewurztraminer);
	        alcohols.add(viognier);
	        alcohols.add(moscato);
	        alcohols.add(prosecco);
	        alcohols.add(cava);
	        alcohols.add(champagne);
	        alcohols.add(brut);
	        alcohols.add(blancDeBlancs);
	        alcohols.add(rose);
	        alcohols.add(sparklingWine);
	        alcohols.add(iceWine);
	        alcohols.add(madeira);
	        alcohols.add(marsala);
	        alcohols.add(drySherry);
	        alcohols.add(creamSherry);
	        alcohols.add(paleAle);
	        alcohols.add(indiaPaleAle);
	        alcohols.add(stout);
	        alcohols.add(pilsner);
	        alcohols.add(wheatBeer);
	        alcohols.add(bock);
	        alcohols.add(porter);
	        alcohols.add(lambic);
	        alcohols.add(kölsch);
	        alcohols.add(saison);
	        alcohols.add(radler);
	        alcohols.add(sake);
	        alcohols.add(plumWine);
	        alcohols.add(koreanSoju);
	        alcohols.add(chineseBaijiu);
	        alcohols.add(sotol);
	        alcohols.add(rakia);
	        alcohols.add(aguardiente);
	        alcohols.add(horchata);
	        alcohols.add(eggnog);
	        alcohols.add(kombucha);
	        alcohols.add(mead);
	        alcohols.add(moonshine);
	        alcohols.add(glogg);
	        alcohols.add(tiswin);
	        alcohols.add(chicha);
	        alcohols.add(pulque);
	        alcohols.add(malort);
	        alcohols.add(akvavit);
	        alcohols.add(gammelDansk);
	        alcohols.add(palinka);
	        alcohols.add(rakija);
	        alcohols.add(pimmsCup);
	        alcohols.add(whiskeySour1);
	        alcohols.add(martini1);
	        alcohols.add(margarita1);
	        alcohols.add(daiquiri11);
	        alcohols.add(mojito111);
	        alcohols.add(pinaColada1);
	        alcohols.add(maiTai11);
	        alcohols.add(longIslandIcedTea);
	        alcohols.add(moscowMule11);
	        alcohols.add(sidecar11);
	        alcohols.add(caipirinha);
	        alcohols.add(cosmopolitan);
	        alcohols.add(oldFashioned1);
	        alcohols.add(negroni11);
	        alcohols.add(whiteRussian1);
	        alcohols.add(bloodyMary);
	        alcohols.add(blueLagoon);
	        alcohols.add(blackRussian1);
	        alcohols.add(sexOnTheBeach);
	        alcohols.add(zombie11);
	        alcohols.add(hurricane);
	        alcohols.add(sazerac111);
	        alcohols.add(corpseReviver11);
	        alcohols.add(grasshopper);
	        alcohols.add(tomCollins1);
	        alcohols.add(mintJulep);
	        alcohols.add(sling);
	        alcohols.add(paloma1);
	        alcohols.add(tequilaSunrise);
	        alcohols.add(alabamaSlammer1);
	        alcohols.add(b52);
	        alcohols.add(kamikaze1);
	        alcohols.add(tequilaSlammer1);
	        alcohols.add(godfather1);
	        alcohols.add(rustyNail1);
	        alcohols.add(robRoy1);
	        alcohols.add(manhattan1);
	        alcohols.add(plantersPunch1);
	        alcohols.add(singaporeSling);
	        alcohols.add(darkAndStormy);
	        alcohols.add(whiteWineSpritzer);
	        alcohols.add(sangria);
	        alcohols.add(blackVelvet);
	        alcohols.add(snakebite);
	        alcohols.add(brassMonkey);
	        alcohols.add(arnoldPalmer);
	        alcohols.add(boilermaker);
	        alcohols.add(depthCharge);
	        alcohols.add(whiskeySmash);
	        alcohols.add(vesper);
	        alcohols.add(tomAndJerry);
	        alcohols.add(gibson);
	        alcohols.add(blackAndTan);
	        alcohols.add(greyhound);
	        alcohols.add(pinkGin);
	        alcohols.add(bocceBall);
	        alcohols.add(redSnapper);
	        alcohols.add(elDiablo);
	        alcohols.add(kirRoyale);
	        alcohols.add(horsesNeck);
	        alcohols.add(caipiroska);
	        alcohols.add(whiskeyCollins);
	        alcohols.add(goldenCadillac);
	        alcohols.add(zombie11);
	        alcohols.add(chocolateMartini1);
	        alcohols.add(painkiller);
	        alcohols.add(aviation1);
	        alcohols.add(robRoy);
	        alcohols.add(blackthorn);
	        alcohols.add(julep);
	        alcohols.add(goldRush1);
	        alcohols.add(oaxacaOldFashioned);
	        alcohols.add(cloverClub1);
	        alcohols.add(vieuxCarre);
	        alcohols.add(stinger);
	        alcohols.add(rumSwizzle);
	        alcohols.add(zombie);
	        alcohols.add(rustyNail);
	        alcohols.add(maryPickford);
	        alcohols.add(hemingwayDaiquiri);
	        alcohols.add(moscowMule11);
	        alcohols.add(maiTai11);
	        alcohols.add(mojito111);
	        alcohols.add(sidecar11);
	        alcohols.add(corpseReviver11);
	        alcohols.add(tomCollins);
	        alcohols.add(sazerac111);
	        alcohols.add(paloma);
	        alcohols.add(negroni11);
	        alcohols.add(boulevardier);
	        alcohols.add(piscoSour);
	        alcohols.add(piscoPunch);
	        alcohols.add(newYorkSour);
	        alcohols.add(vodkaCollins);
	        alcohols.add(french75);
	        alcohols.add(bellini);
	        alcohols.add(darkNStormy1);
	        alcohols.add(cloverClub);
	        alcohols.add(corpseReviver);
	        alcohols.add(goldRush);
	        alcohols.add(daiquiri11);
	        alcohols.add(sazerac111);
	        alcohols.add(zombie22);
	        alcohols.add(mojito111);
	        alcohols.add(maiTai);
	        alcohols.add(moscowMule);
	        alcohols.add(sidecar);
	        alcohols.add(whiteLady);
	        alcohols.add(oldCuban);
	        alcohols.add(frenchConnection);
	        alcohols.add(wardEight);
	        alcohols.add(plantersPunch);
	        alcohols.add(kamikaze);
	        alcohols.add(godfather);
	        alcohols.add(tequilaSlammer);
	        alcohols.add(alabamaSlammer);
	        alcohols.add(seaBreeze);
	        alcohols.add(cubaLibre);
	        alcohols.add(blackRussian);
	        alcohols.add(caipirissima);
	        alcohols.add(darkNStormy);
	        alcohols.add(kir);
	        alcohols.add(whiteRussian);
	        alcohols.add(chocolateMartini);
	        alcohols.add(aviation);
	        alcohols.add(whiskeySour);
	        alcohols.add(amarettoSour);
	        alcohols.add(mojito);
	        alcohols.add(daiquiri);
	        alcohols.add(pinaColada);
	        alcohols.add(margarita);
	        alcohols.add(martini);
	        alcohols.add(negroni);
	        alcohols.add(sazerac);
	        alcohols.add(manhattan);
	        alcohols.add(oldFashioned);
	        alcohols.add(whiskeySour2);
	        alcohols.add(tomCollins2);
	        alcohols.add(caipirinha2);
	        alcohols.add(mojito3);
	        alcohols.add(piscoSour3);
	        alcohols.add(daiquiri4);
	        alcohols.add(pinaColada4);
	        alcohols.add(margarita5);
	        alcohols.add(moscowMule6);
	        alcohols.add(negroni7);
	        alcohols.add(sidecar8);
	        alcohols.add(maiTai9);
	        alcohols.add(zombie7);
	        alcohols.add(sazerac6);
	        alcohols.add(boulevardier5);
	        alcohols.add(blackRussian44);
	        
	        System.out.println("Total : " + alcohols.size());
	        
	        Iterator<AlcoholDTO> itr = alcohols.iterator();
	        while (itr.hasNext()) {
	            AlcoholDTO alcoholDTO1 = itr.next();
	            System.out.println("Name: " + alcoholDTO1.getName());
	        }
	        
	        
	    }
	}

